### ISSUE TITLE
create inner and outer meshes for wall-mounted lamp

### ISSUE THREAD

**Issue by shawnfromportland** [shawnfromportland/thespanishconnectionVR#1]
so that inner wireframe can be a light emitter

**Comment by ToxSam** [comment]
ahaa

**Comment by shawnfromportland** [comment]
i got the new outer lamp mesh, i need a mesh that fits inside the wall lamps, representing the glowing glass.

**Comment by shawnfromportland** [comment]
this is no longer needed because there will be no light emitters in the experience due to performance constraints
