### ISSUE TITLE
make the main passenger compartment an empty slot in the main train car mesh

### ISSUE THREAD

**Issue by shawnfromportland** [shawnfromportland/thespanishconnectionVR#20]
no matter what i tried i couldnt get smooth shadows being cast onto the table and chairs in the compartment, and i think its because of the poly count in the train car mesh. just remove this entire compartment where i have the camera in this screenshot, and i will add in the bench seats and table and lamp using the separate individual meshes. i think this will allow for smooth shadows.
![screen shot 2017-02-03 at 12 20 25 pm](https://cloud.githubusercontent.com/assets/1243245/22607238/cedeefac-ea0b-11e6-919a-8fb24d21e399.png)

**Comment by shawnfromportland** [comment]
make the red empty space
![screen-shot-2017-02-03-at-12 20 25-pm](https://cloud.githubusercontent.com/assets/1243245/22607288/132a8158-ea0c-11e6-932e-4f90cf9c473b.png)

**Comment by ToxSam** [comment]
sure! no probs, I'll get on it in a few

**Comment by shawnfromportland** [comment]
this probably just comes down to  our own person preferences IRL where we like to sit on the train, but i wanted the back right booth removed, and you gave me a mesh with the middle left booth removed.  it's ok, ive built up a scene in that position. the shadows are better but they could still use work. i will have another demo soon

**Comment by shawnfromportland** [comment]
im still hoping we can get the empty booth to be the rear right.

**Comment by shawnfromportland** [comment]
this is no longer needed since I am not going to do any lighting in the app. it can all be one mesh, i think that is the most efficient way
