### ISSUE TITLE
please import human dummy mesh into unity cloud

### ISSUE THREAD

**Issue by shawnfromportland** [shawnfromportland/thespanishconnectionVR#29]
let me have the dummy mesh shown here:
![img_20170201_104912_056](https://cloud.githubusercontent.com/assets/1243245/22771367/28b48c4c-ee4b-11e6-9ca0-3cae98b540cc.jpg)

i want to experiment with creating an analog of the users' body. in the experience "androids dream" it works decently having a body, when you position yourself in the same position and you are male
https://www.youtube.com/watch?v=5qEZi7HhPFo

**Comment by ToxSam** [comment]
Sure no probs will upload also one without head

**Comment by ToxSam** [comment]
Uploaded Mesh_joe_01 and one without head
